import type { EventRecord } from "./types";

const createdAt = "2026-08-20T09:00:00.000Z";

export const demoEvents: EventRecord[] = [
  {
    id: "evt-open-source-lab",
    slug: "open-source-systems-lab",
    title: "Open Source Systems Lab",
    summary: "A hands-on DEMO event about maintainable open source services.",
    description:
      "This fictional first-party DEMO event uses practical sessions to explore issue triage, release automation, and sustainable maintainer workflows. It is not a real third-party listing.",
    image: "/images/event1.png",
    venue: "Demo Harbor Hall",
    location: "San Francisco, CA",
    startsAt: "2026-09-18T16:00:00.000Z",
    endsAt: "2026-09-18T23:00:00.000Z",
    mode: "hybrid",
    audience: "Maintainers and backend engineers",
    topics: ["Open Source", "DevOps", "Backend"],
    organizerId: "organizer-demo",
    organizerName: "DevEvent Demo Programs",
    sourceLabel: "First-party DEMO catalog",
    verifiedAt: "2026-08-20T09:00:00.000Z",
    freshnessDays: 90,
    status: "approved",
    capacity: 2,
    registrationCount: 0,
    attendeeListVisibility: "organizer-only",
    speakers: [
      {
        name: "Maya Chen",
        title: "Fictional maintainer",
        bio: "Demo speaker profile for repository governance workshops.",
      },
    ],
    schedule: [
      { startsAt: "2026-09-18T16:00:00.000Z", title: "Maintainer intake clinic", speaker: "Maya Chen" },
      { startsAt: "2026-09-18T18:00:00.000Z", title: "Release pipelines lab" },
    ],
    recordings: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "evt-accessible-web",
    slug: "accessible-web-clinic",
    title: "Accessible Web Clinic",
    summary: "A first-party DEMO clinic for testing accessible interfaces.",
    description:
      "This fictional workshop covers keyboard navigation, semantic markup, and useful screen-reader testing. It is DEMO data owned by DevEvent.",
    image: "/images/event2.png",
    venue: "Online DEMO room",
    location: "Online",
    startsAt: "2026-10-08T17:00:00.000Z",
    endsAt: "2026-10-08T20:30:00.000Z",
    mode: "online",
    audience: "Frontend engineers and designers",
    topics: ["Accessibility", "Frontend"],
    organizerId: "organizer-demo",
    organizerName: "DevEvent Demo Programs",
    sourceLabel: "First-party DEMO catalog",
    verifiedAt: "2026-08-22T12:00:00.000Z",
    freshnessDays: 90,
    status: "approved",
    capacity: 40,
    registrationCount: 0,
    attendeeListVisibility: "organizer-only",
    speakers: [
      {
        name: "Jordan Ellis",
        title: "Fictional accessibility engineer",
        bio: "Demo speaker profile focused on inclusive UI testing.",
      },
    ],
    schedule: [
      { startsAt: "2026-10-08T17:00:00.000Z", title: "Keyboard testing", speaker: "Jordan Ellis" },
      { startsAt: "2026-10-08T18:30:00.000Z", title: "Screen-reader lab" },
    ],
    recordings: [
      {
        title: "Demo follow-up: accessible interface checklist",
        url: "https://www.w3.org/WAI/test-evaluate/",
      },
    ],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "evt-edge-runtime",
    slug: "edge-runtime-retrospective",
    title: "Edge Runtime Retrospective",
    summary: "A completed DEMO roundtable about edge application tradeoffs.",
    description:
      "A fictional first-party DEMO event retained to demonstrate past-event search, schedules, and recording metadata.",
    image: "/images/event3.png",
    venue: "Demo Foundry",
    location: "Austin, TX",
    startsAt: "2026-07-11T15:00:00.000Z",
    endsAt: "2026-07-11T19:00:00.000Z",
    mode: "in-person",
    audience: "Platform engineers",
    topics: ["Edge", "Performance"],
    organizerId: "organizer-demo",
    organizerName: "DevEvent Demo Programs",
    sourceLabel: "First-party DEMO catalog",
    verifiedAt: "2026-08-18T12:00:00.000Z",
    freshnessDays: 90,
    status: "approved",
    capacity: 24,
    registrationCount: 0,
    attendeeListVisibility: "organizer-only",
    speakers: [],
    schedule: [{ startsAt: "2026-07-11T15:00:00.000Z", title: "Latency budget retrospective" }],
    recordings: [
      { title: "Demo retrospective notes", url: "https://developer.mozilla.org/en-US/docs/Web/API" },
    ],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "evt-cancelled-demo",
    slug: "cancelled-demo-meetup",
    title: "Cancelled Demo Meetup",
    summary: "A cancelled first-party DEMO listing used to explain event states.",
    description: "This fictional event is intentionally cancelled and cannot accept registrations.",
    image: "/images/event4.png",
    venue: "Demo Studio",
    location: "New York, NY",
    startsAt: "2026-09-02T22:00:00.000Z",
    endsAt: "2026-09-03T00:00:00.000Z",
    mode: "in-person",
    audience: "Developers",
    topics: ["Community"],
    organizerId: "organizer-demo",
    organizerName: "DevEvent Demo Programs",
    sourceLabel: "First-party DEMO catalog",
    verifiedAt: "2026-08-19T12:00:00.000Z",
    freshnessDays: 90,
    status: "cancelled",
    moderationNote: "Cancelled by the demo organizer.",
    capacity: 30,
    registrationCount: 0,
    attendeeListVisibility: "organizer-only",
    speakers: [],
    schedule: [],
    recordings: [],
    createdAt,
    updatedAt: createdAt,
  },
];

export const DEMO_TOPICS = Array.from(new Set(demoEvents.flatMap((event) => event.topics))).sort();
