import type { EventRecord } from "./types";

const common = {
  source: "demo" as const,
  sourceLabel: "DevEvent portfolio demo — not a live third-party listing",
  lastVerifiedAt: "2026-08-20T12:00:00.000Z",
  freshUntil: "2026-12-31T23:59:59.000Z",
  organizerId: "demo-organizer",
  organizerName: "DevEvent Demo Studio",
  createdAt: "2026-08-20T12:00:00.000Z",
  updatedAt: "2026-08-20T12:00:00.000Z",
};

export const demoEvents: EventRecord[] = [
  {
    ...common,
    slug: "open-source-systems-lab",
    title: "Open Source Systems Lab",
    description: "A hands-on demo event about profiling and improving open-source systems.",
    overview: "Work through a realistic performance investigation with maintainers, then compare the trade-offs behind each fix.",
    image: "/images/event1.png",
    venue: "Demo Hall A",
    location: "London, UK",
    startsAt: "2026-09-18T09:00:00.000Z",
    endsAt: "2026-09-18T16:30:00.000Z",
    timezone: "Europe/London",
    mode: "hybrid",
    audience: "Backend engineers and open-source contributors",
    topics: ["Open Source", "Performance", "Systems"],
    moderationStatus: "approved",
    capacity: 40,
    registeredCount: 2,
    speakers: [
      { name: "Maya Chen", role: "Demo maintainer", bio: "Maintains the fictional Northstar runtime used in this portfolio demo." },
      { name: "Owen Brooks", role: "Performance engineer", bio: "Teaches repeatable profiling techniques using demo workloads." },
    ],
    schedule: [
      { time: "09:00", title: "Doors and environment setup" },
      { time: "10:00", title: "Finding the hot path", speaker: "Maya Chen" },
      { time: "13:00", title: "Hands-on profiling lab", speaker: "Owen Brooks" },
      { time: "15:30", title: "Review and maintainer Q&A" },
    ],
    recordings: [],
  },
  {
    ...common,
    slug: "responsible-ai-build-night",
    title: "Responsible AI Build Night",
    description: "A small demo workshop for evaluating AI product behavior before release.",
    overview: "Teams use a fictional product brief to create evaluation cases, document limitations, and present a release recommendation.",
    image: "/images/event4.png",
    venue: "Demo Workshop Room",
    location: "Toronto, Canada",
    startsAt: "2026-10-08T22:00:00.000Z",
    endsAt: "2026-10-09T01:00:00.000Z",
    timezone: "America/Toronto",
    mode: "offline",
    audience: "Application developers and product engineers",
    topics: ["AI", "Testing", "Product"],
    moderationStatus: "approved",
    capacity: 24,
    registeredCount: 0,
    speakers: [{ name: "Rina Patel", role: "Demo facilitator", bio: "Builds evaluation exercises for fictional AI products." }],
    schedule: [
      { time: "18:00", title: "Evaluation framing", speaker: "Rina Patel" },
      { time: "18:45", title: "Team build session" },
      { time: "20:15", title: "Release reviews" },
    ],
    recordings: [],
  },
  {
    ...common,
    slug: "frontend-accessibility-clinic",
    title: "Frontend Accessibility Clinic",
    description: "A completed demo clinic covering keyboard and screen-reader testing.",
    overview: "A past event retained to demonstrate archive filtering and recording metadata.",
    image: "/images/event2.png",
    venue: "Online demo room",
    location: "Online",
    startsAt: "2026-07-16T16:00:00.000Z",
    endsAt: "2026-07-16T18:00:00.000Z",
    timezone: "UTC",
    mode: "online",
    audience: "Frontend developers",
    topics: ["Accessibility", "Frontend", "Testing"],
    moderationStatus: "approved",
    capacity: 100,
    registeredCount: 38,
    speakers: [{ name: "Alex Rivera", role: "Demo accessibility lead", bio: "Reviews accessible interfaces in this fictional event series." }],
    schedule: [{ time: "16:00", title: "Keyboard testing clinic", speaker: "Alex Rivera" }],
    recordings: [{ title: "Demo follow-up: W3C accessibility evaluation resources", url: "https://www.w3.org/WAI/test-evaluate/" }],
  },
  {
    ...common,
    slug: "cloud-incident-tabletop",
    title: "Cloud Incident Tabletop",
    description: "A cancelled demo event retained so cancellation behavior is visible.",
    overview: "This fictional exercise was cancelled; active attendees receive the cancellation reason through the product flow.",
    image: "/images/event6.png",
    venue: "Demo Operations Center",
    location: "Berlin, Germany",
    startsAt: "2026-09-02T15:00:00.000Z",
    endsAt: "2026-09-02T18:00:00.000Z",
    timezone: "Europe/Berlin",
    mode: "hybrid",
    audience: "Platform and reliability engineers",
    topics: ["Cloud", "DevOps", "Reliability"],
    moderationStatus: "approved",
    cancelledAt: "2026-08-19T10:00:00.000Z",
    cancellationReason: "Demo venue became unavailable.",
    capacity: 30,
    registeredCount: 0,
    speakers: [],
    schedule: [{ time: "17:00", title: "Tabletop exercise" }],
    recordings: [],
  },
];
